

services:

  postgres:
    image: 'postgres:latest'
    container_name: '10AnimeDB'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: 10AnimeDB

    ports:
      - "6000:5432"


