version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    container_name: '10AnimeDB'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "5432:5432"


