version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    container_name: '10AnimeDB'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    ports:
      - "5432:5432"
    networks:
      - keycloak-network

  keycloak:
    image: "quay.io/keycloak/keycloak:25.0.4"
    container_name: "keycloak"
    ports:
      - "9000:9000"  # Custom port mapping
    restart: "unless-stopped"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "1234"
      DB_VENDOR: "postgres"
      DB_ADDR: "postgres"
      DB_DATABASE: "${DB_NAME}"
      DB_USER: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
    command: ["start-dev", "--http-port=9000"]  # Set custom HTTP port
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
