

services:
  app:
    container_name: app
    image: server:1.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/10AnimeDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - postgres
  postgres:
    image: 'postgres:latest'
    container_name: '10AnimeDB'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: 10AnimeDB

    ports:
      - "6000:5432"


